# Generated by Django 4.2.2 on 2023-06-19 12:51

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, unique=True)),
                ('ticket_goal', models.CharField(editable=False, max_length=128)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('burn_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ticket_count', models.IntegerField(default=0)),
                ('ticket_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_done', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('previous_round', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='lottery.roundinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(editable=False, max_length=6, validators=[django.core.validators.MaxLengthValidator(6), django.core.validators.MinLengthValidator(6)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottery.roundinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoundWinners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_count', models.IntegerField(default=0)),
                ('winner_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), default=list, size=None)),
                ('type', models.CharField(choices=[('win_1', 'win_1'), ('win_2', 'win_2'), ('win_3', 'win_3'), ('win_4', 'win_4'), ('win_5', 'win_5'), ('win_6', 'win_6')], default=(('win_1', 'win_1'), ('win_2', 'win_2'), ('win_3', 'win_3'), ('win_4', 'win_4'), ('win_5', 'win_5'), ('win_6', 'win_6')))),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lottery.roundinfo')),
            ],
        ),
        migrations.CreateModel(
            name='RoundDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('type', models.CharField(choices=[('win_1', 'win_1'), ('win_2', 'win_2'), ('win_3', 'win_3'), ('win_4', 'win_4'), ('win_5', 'win_5'), ('win_6', 'win_6')], default=(('win_1', 'win_1'), ('win_2', 'win_2'), ('win_3', 'win_3'), ('win_4', 'win_4'), ('win_5', 'win_5'), ('win_6', 'win_6')))),
                ('ratio', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottery.roundinfo')),
            ],
        ),
    ]
