# Generated by Django 4.1.4 on 2023-06-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rounddetail',
            name='type',
            field=models.CharField(choices=[('win_1', 'win_1'), ('win_2', 'win_2'), ('win_3', 'win_3'), ('win_4', 'win_4'), ('win_5', 'win_5'), ('win_6', 'win_6')], default=(('win_1', 'win_1'), ('win_2', 'win_2'), ('win_3', 'win_3'), ('win_4', 'win_4'), ('win_5', 'win_5'), ('win_6', 'win_6')), max_length=10),
        ),
        migrations.AlterField(
            model_name='roundwinners',
            name='type',
            field=models.CharField(choices=[('win_1', 'win_1'), ('win_2', 'win_2'), ('win_3', 'win_3'), ('win_4', 'win_4'), ('win_5', 'win_5'), ('win_6', 'win_6')], default=(('win_1', 'win_1'), ('win_2', 'win_2'), ('win_3', 'win_3'), ('win_4', 'win_4'), ('win_5', 'win_5'), ('win_6', 'win_6')), max_length=10),
        ),
    ]
