# Generated by Django 4.2.2 on 2023-06-16 08:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='round_number',
            new_name='round',
        ),
        migrations.AddField(
            model_name='roundinfo',
            name='number',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.CharField(editable=False, max_length=6, validators=[django.core.validators.MaxLengthValidator(6), django.core.validators.MinLengthValidator(6)]),
        ),
    ]
