# Generated by Django 4.2.2 on 2023-06-16 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0002_rename_round_number_ticket_round_roundinfo_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundWinnerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('type', models.CharField(choices=[('win_1', 'win_1'), ('win_2', 'win_2'), ('win_3', 'win_3'), ('win_4', 'win_4'), ('win_5', 'win_5'), ('win_6', 'win_6')], default=(('win_1', 'win_1'), ('win_2', 'win_2'), ('win_3', 'win_3'), ('win_4', 'win_4'), ('win_5', 'win_5'), ('win_6', 'win_6')))),
                ('total_amount_by_type', models.FloatField()),
                ('ratio', models.FloatField()),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottery.roundinfo')),
            ],
        ),
    ]
