# Generated by Django 4.2.2 on 2023-06-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0002_alter_rounddetail_type_alter_roundwinners_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundinfo',
            name='ticket_goal',
            field=models.CharField(editable=False, max_length=6),
        ),
    ]
