# Generated by Django 4.2.2 on 2023-06-16 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0003_roundwinnerdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roundwinnerdetail',
            old_name='total_amount_by_type',
            new_name='total_amount',
        ),
    ]
