# Generated by Django 4.2.2 on 2023-06-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0004_rename_total_amount_by_type_roundwinnerdetail_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundinfo',
            name='lock_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='roundwinnerdetail',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roundwinnerdetail',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
    ]
