#version: "3.5"
#services:
#  web:
#    container_name: penc
#    restart: always
#    build: .
#    depends_on:
#      - db
#      - cache
#    ports:
#      - "8020:80"
#    volumes:
#      - "/var/services/penc/media:/var/services/penc/media"
#      - "/var/services/penc/vault:/var/services/penc/vault"
#      - "/var/services/penc/static:/var/services/penc/static"
#    env_file:
#      - assets/base.env
#    networks:
#      - main
#  db:
#    container_name: penc-db
#    restart: always
#    image: "postgis/postgis:13-3.1-alpine"
#    env_file:
#      - assets/db.env
#    volumes:
#      - "/var/services/penc/db:/var/lib/postgresql/data"
#    expose:
#      - "5432"
#    networks:
#      - main
#  cache:
#    container_name: penc-cache
#    restart: always
#    image: "redis:6-alpine"
#    expose:
#      - "6379"
#    networks:
#      - main
#
#networks:
#  main:
#    name: penc
#    driver: bridge
