# Generated by Django 4.2.2 on 2023-07-01 13:23

from django.db import migrations, models
import user.utils


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wallet_address',
            field=models.CharField(max_length=42, unique=True, validators=[user.utils.validate_eth_address]),
        ),
    ]
