# Generated by Django 4.2.2 on 2023-06-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='temp_transaction_ref',
            field=models.CharField(blank=True, default=None, max_length=36, null=True),
        ),
    ]
