# Generated by Django 4.2.2 on 2023-06-22 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_cashoutrequest_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashoutrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='cashoutrequest',
            name='wallet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='wallet.wallet'),
            preserve_default=False,
        ),
    ]
