# Generated by Django 4.2.2 on 2023-06-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_remove_cashoutrequest_user_cashoutrequest_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashoutrequest',
            name='type',
            field=models.CharField(choices=[('usd', 'usd'), ('eth', 'eth'), ('btc', 'btc')], default='usd', max_length=5),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency_swap',
            field=models.CharField(blank=True, choices=[('usd', 'usd'), ('eth', 'eth'), ('btc', 'btc')], default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency_type',
            field=models.CharField(choices=[('usd', 'usd'), ('eth', 'eth'), ('btc', 'btc')], default='usd', max_length=5),
        ),
    ]
