# Generated by Django 4.2.2 on 2023-06-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_cashoutrequest_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount_swap',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
    ]
