# Generated by Django 4.2.2 on 2023-07-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_transaction_amount_swap'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='confirm',
            field=models.JSONField(default='confirm', verbose_name='confirm'),
            preserve_default=False,
        ),
    ]
